ctng_cpu_arch:
  - i686  # [linux32]
  - x86_64  # [linux64]
  - powerpc64le  # [ppc64le]
  - aarch64  # [aarch64]
ctng_vendor:
  - conda_cos6  # [linux32 or linux64]
  - conda_cos7  # [aarch64 or ppc64le]

