{% set name = "binutils" %}
{% set version = "2.35" %}
{% set chost = ctng_cpu_arch ~ "-" ~ ctng_vendor ~ "-linux-gnu-" %}
{% set build_num = 4 %}

package:
  name: binutils_split
  version: {{ version }}

source:
  - url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.bz2
    sha256: 7d24660f87093670738e58bcc7b7b06f121c0fcb0ca8fc44368d675a5ef9cff7
    folder: .

  # Get the patches from crosstool-ng
  # Using https://github.com/crosstool-ng/crosstool-ng/pull/1309
  - url: https://github.com/crosstool-ng/crosstool-ng/archive/db980376cdf74ada7b085e422c52c36a2ce85cd3.tar.gz
    sha256: 4a0be5a8d3a2076391ef096ceeaa5d6b207ac424f6a18913894bce1dc434c463
    folder: crosstool_ng

build:
  number: {{ build_num }}
  skip: true  # [not linux]
  detect_binary_files_with_prefix: false

requirements:
  build:
  host:
  run:

outputs:
  - name: ld_impl_{{ target_platform }}
    script: install_ld.sh
    build:
      merge_build_host: false
      detect_binary_files_with_prefix: false
    requirements:
      build:
      host:
      run:
      run_constrained:
        - gcc_impl_{{ target_platform }} !=7.2.0,!=7.3.0,!=8.2.0,!=5.4.0
        - gxx_impl_{{ target_platform }} !=7.2.0,!=7.3.0,!=8.2.0,!=5.4.0
        - gfortran_impl_{{ target_platform }} !=7.2.0,!=7.3.0,!=8.2.0,!=5.4.0
        - binutils_impl_{{ target_platform }} {{ version }}
    test:
      commands:
        - {{ chost }}ld --help

  - name: binutils_impl_{{ target_platform }}
    script: install_binutils.sh
    build:
      merge_build_host: false
      detect_binary_files_with_prefix: false
      ignore_run_exports:
        - __glibc
    requirements:
      build:
      host:
        - ld_impl_{{ target_platform }} {{ version }}
      run:
        - {{ pin_subpackage("ld_impl_" ~ target_platform, exact=True) }}
        - sysroot_{{ target_platform }}
      run_constrained:
        - gcc_impl_{{ target_platform }} !=7.2.0,!=7.3.0,!=8.2.0,!=5.4.0
        - gxx_impl_{{ target_platform }} !=7.2.0,!=7.3.0,!=8.2.0,!=5.4.0
        - gfortran_impl_{{ target_platform }} !=7.2.0,!=7.3.0,!=8.2.0,!=5.4.0
    test:
      downstreams:
        - gfortran_impl_{{ target_platform }}
        - gcc_impl_{{ target_platform }}
      commands:
        - {{ chost }}addr2line --help
        - {{ chost }}ar --help
        - {{ chost }}as --help
        - {{ chost }}c++filt --help
        - {{ chost }}elfedit --help
        - {{ chost }}gprof --help
        - {{ chost }}ld --help
        - {{ chost }}ld.bfd --help
        - {{ chost }}ld.gold --help
        - {{ chost }}nm --help
        - {{ chost }}objcopy --help
        - {{ chost }}objdump --help
        - {{ chost }}ranlib --help
        - {{ chost }}readelf --help
        - {{ chost }}size --help
        - {{ chost }}strings --help
        - {{ chost }}strip --help

  - name: binutils
    script: install_binutils_symlinks.sh
    build:
      merge_build_host: false
      detect_binary_files_with_prefix: false
    requirements:
      build:
      host:
        - binutils_impl_{{ target_platform }}
      run:
        - {{ pin_subpackage("binutils_impl_" ~ target_platform, max_pin="x.x.x") }}
    test:
      commands:
        - $PREFIX/bin/addr2line --help
        - $PREFIX/bin/ar --help
        - $PREFIX/bin/as --help
        - $PREFIX/bin/c++filt --help
        - $PREFIX/bin/elfedit --help
        - $PREFIX/bin/gold --help
        - $PREFIX/bin/gprof --help
        - $PREFIX/bin/ld --help
        - $PREFIX/bin/ld.bfd --help
        - $PREFIX/bin/ld.gold --help
        - $PREFIX/bin/nm --help
        - $PREFIX/bin/objcopy --help
        - $PREFIX/bin/objdump --help
        - $PREFIX/bin/ranlib --help
        - $PREFIX/bin/readelf --help
        - $PREFIX/bin/size --help
        - $PREFIX/bin/strings --help
        - $PREFIX/bin/strip --help

about:
  home: https://www.gnu.org/software/binutils/
  license: GPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LIB
    - COPYING3
    - COPYING3.LIB
  summary: |
    A set of programming tools for creating and managing binary programs, object files,
    libraries, profile data, and assembly source code.

extra:
  recipe-maintainers:
    - frol
    - isuruf
    - jjhelmus
    - beckermr
