{% set name = "binutils" %}
{% set version = "2.32" %}
{% set sha256 = "de38b15c902eb2725eac6af21183a5f34ea4634cb0bcef19612b50e5ed31072d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison
    - flex

test:
  commands:
    - addr2line --help
    - ar --help
    - as --help
    - c++filt --help
    - elfedit --help
    - gold --help
    - gprof --help
    - ld --help
    - ld.bfd --help
    - ld.gold --help
    - nm --help
    - objcopy --help
    - objdump --help
    - ranlib --help
    - readelf --help
    - size --help
    - strings --help
    - strip --help

about:
  home: https://www.gnu.org/software/binutils/
  license: GPL 3
  summary: A set of programming tools for creating and managing binary programs, object files, libraries, profile data, and assembly source code.

extra:
  recipe-maintainers:
    - frol
