# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "v13godeiXlqM1MM21AC9FzSrj+pqYbXi/mX7PvFcbwsPiHHp26vYxy/syGilWA712cTf0SkNjFa/fwVuPRaBv6dKZ7IPMsy5ZOCMtJ/1grSLSCdGlXoIaxHttZHFkBIITNQMlgxnK0pS6qxpkgaY+wEyXze0HPPaB02mk/ASnx/mVV9OkK0CZLt/RKGr0CitTpyF4XIkuzIUaJRe/t/N+2/U3nqHECzADdJoKk09girKfF0R6wjSTy4LZCcxkaGm4LMpK5ui7ncNDW5RbC38qKqkpHdxaWYolYckYZ4eLq+vfuRr65NLX2R4J9ti3yl7AXTPFZbkVEzMdv38u+UixK4Kslk9aG5EBGM7bvO/cIG21BhC0tOIQ2NUlDI9owrO5QtEmamjM9qXxSsi1/64qKFz3w6goGr7zpPkrXBOzFO3gC9N+5KQdE9X8B4y3NG920DQJGq0lNJiga9/SdkaLd2vgBEnyfJp1BbotJfohuTCl83OAifZZADJ34nF5uI4fG9ciC2FK4ojqbL7dQZbf3t9IX1EzSTRAqtjjmNkS/C751MH+l4LwHg+Eu4VEAmHG7gnCi4HOGHNPGU+t7Y234O0hN1dr8GhTWF5nW/ficT1pjpExdwU2NzwqUfn7hgolmi/G7Adx/KSzZkCJQlg2whTRnhgTiQnzqswGNLOjOM="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi